ip_method: 0
manual_ip: 192.168.1.2
dns: 8.8.8.8
gateway: 192.168.1.1
subnet: 255.255.255.0
joint_characteristics:
  - effort_correction: 1.10000002
    friction_transition_velocity: 0.0399999991
    friction_constant_term: 0.239999995
    friction_coulomb_coef: 0
    friction_viscous_coef: 0
    continuity_factor: 2
  - effort_correction: 1.10000002
    friction_transition_velocity: 0.0399999991
    friction_constant_term: 0.0799999982
    friction_coulomb_coef: 0.100000001
    friction_viscous_coef: 0
    continuity_factor: 2
  - effort_correction: 1.10000002
    friction_transition_velocity: 0.0399999991
    friction_constant_term: 0.159999996
    friction_coulomb_coef: 0.119999997
    friction_viscous_coef: 0
    continuity_factor: 2
  - effort_correction: 1.25
    friction_transition_velocity: 0.00999999978
    friction_constant_term: -0.00999999978
    friction_coulomb_coef: 0.0199999996
    friction_viscous_coef: 0
    continuity_factor: 2
  - effort_correction: 1.14999998
    friction_transition_velocity: 0.00999999978
    friction_constant_term: 0.0399999991
    friction_coulomb_coef: 0.0199999996
    friction_viscous_coef: 0
    continuity_factor: 2
  - effort_correction: 1.14999998
    friction_transition_velocity: 0.00999999978
    friction_constant_term: 0.0599999987
    friction_coulomb_coef: 0
    friction_viscous_coef: 0
    continuity_factor: 2
  - effort_correction: 1.14999998
    friction_transition_velocity: 8.74999969e-05
    friction_constant_term: 6.85714245
    friction_coulomb_coef: 0
    friction_viscous_coef: 0
    continuity_factor: 2
